src/app/urls.py
# myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

src/blogs/urls.py
# myblog/blogs/urls.py

from django.urls import path
from . import views

# set the application namespace
# https://docs.djangoproject.com/ja/2.0/intro/tutorial03/
app_name = 'blogs'

urlpatterns = [
    # 一覧表示のURL: /
    path('', views.IndexView.as_view(), name='index'),  # url is /

    # 新規作成のURL: /post/create/
    path('post/create/', views.CreateView.as_view(), name='create'),

    # 以下では記事IDを 123 とします
    # 詳細表示のURL: /post/123/
    path('post/<int:pk>/', views.DetailView.as_view(), name='detail'),

    # 内容更新のURL: /post/123/update/
    path('post/<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    
    # 記事削除のURL: /post/123/delete/
    path('post/<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

src/blogs/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

src/blogs/views.py
# myblog/blogs/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Post

class IndexView(generic.ListView):
    model = Post
    paginate_by = 5
    ordering = ['-updated_at']
    template_name = 'blogs/index.html'

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blogs/detail.html'

class CreateView(generic.edit.CreateView):
    model = Post
    fields = '__all__'  # ['title', 'text', 'author']
    success_url = reverse_lazy('blogs:index')
    template_name = 'blogs/create.html'

class UpdateView(generic.edit.UpdateView):
    model = Post
    fields = '__all__'  # ['title', 'text', 'author']
    success_url = reverse_lazy('blogs:index')
    template_name = 'blogs/update.html'
    

class DeleteView(generic.edit.DeleteView):
    model = Post
    success_url = reverse_lazy('blogs:index')
    template_name = 'blogs/delete.html'

src/blogs/templates/blogs/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'blogs/css/style.css' %}" rel="stylesheet">
    <title>Blog App - Django2 Tutorial</title>
</head>
<body>
<div class="container">
    <header>
        <p class="site-name"><a href="{% url 'blogs:index' %}">My Blog App</a></p>
        <nav>
            <ul>
                <li><a href="{% url 'blogs:index' %}">Home</a></li>
                <li><a href="{% url 'blogs:create' %}" class="act">Add New Post</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

src/blogs/templates/blogs/create.html
{% extends 'blogs/base.html' %}

{% block content %}
<h1>Add New Post</h1>
<section class="post-form">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Save</button>
    </form>
</section>
{% endblock %}

src/blogs/templates/blogs/delete.html
{% extends 'blogs/base.html' %}

{% block content %}
<h1>Delete Post</h1>
<section class="post-form">
    <p>Are you sure you want to delete "{{ object.title }}" ?</p>
    <form action="" method="post">{% csrf_token %}
        <button type="submit" class="submit delete">Delete</button>
    </form>
</section>
<section>
    <p><a href="javascript:history.back()">&lt; Back</a></p>
</section>
{% endblock %}

src/blogs/templates/blogs/detail.html
{% extends 'blogs/base.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
<section class="post-text">
    {{ object.text|linebreaksbr }}
</section>
<section class="post-date">
    <p>Created:&nbsp;{{ object.created_at }}<span>/</span>Updated:&nbsp;{{ object.updated_at }}</p>
</section>
<section class="post-edit">
    <a class="act" href="{% url 'blogs:update' post.pk %}">Edit</a>
    <a class="act" href="{% url 'blogs:delete' post.pk %}">Delete</a>
</section>
<section>
    <p><a href="javascript:history.back()">&lt; Back</a></p>
</section>
{% endblock %}

src/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
<h1>My Articles</h1>

<section class="post-list">
    <ul>
        {% for post in object_list %}
        <li>
            <h2><a href="{% url 'blogs:detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text }}</p>
        </li>
        {% empty %}
        <li class="no-post">
            <p>No articles yet.</p>
            <p><a class="act" href="{% url 'blogs:create' %}">Add New Post</a></p></li>
        {% endfor %}
    </ul>
</section>

{% if is_paginated %}
<section class="pagination">
    <ul>
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
            {% else %}
            &lt;&lt; Prev
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
            {% else %}
            Next &gt;&gt;
            {% endif %}
        </li>
    </ul>
</section>
{% endif %}
{% endblock %}

src/blogs/templates/blogs/update.html
{% extends 'blogs/base.html' %}

{% block content %}
<h1>Edit post</h1>
<section class="post-form">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Update</button>
    </form>
</section>
{% endblock %}